<%@ Page Language="C#" AutoEventWireup="true" CodeFile="aexpire.aspx.cs" Inherits="aexpire" %>


<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>WARM HEARTS</title>
    
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="assets/css/fontawesome.css">
    <link rel="stylesheet" href="assets/css/templatemo-grad-school.css">
    <link rel="stylesheet" href="assets/css/owl.css">
    <link rel="stylesheet" href="assets/css/lightbox.css">
<!--
    
TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
      </head>

 <body style="background-image:url(assets/images/choosing-bg.jpg)">

     <form runat="server">
      <!--header-->
      <header class="main-header clearfix">
          <div class="logo">
              <a href="#" style="font-size:larger;"><em>AD</em>MIN</a>
          </div>
          <nav id="nav" class="main-nav" role="navigation">
              <ul class="main-menu">
                  <li><a href="admin.aspx">Home</a></li>
                  <li><a href="adonordetails.aspx">Donor's details</a></li>
                  <li><a href="arecdetails.aspx">Receivers details</a></li>
                  
                  <li><a href="aeditpwd.aspx">Edit Password</a></li>
                  <li><a href="ablog.aspx">Edit Blog</a></li>
                  <li><a href="aorphanage.aspx">Edit Orphanage</a></li>
                  <li><a href="aexpire.aspx">Delete Food Details</a></li>
                  <!-- <li><a href="#section5">Video</a></li> -->
                  
                  
            
                  <li><a href="signin.aspx">Logout</a></li>
              </ul>
          </nav>
          <hr/>
      </header>
        <br /><br /><br /><br /><br /><br />
                    <center><h1 style="color:aliceblue">DELETING THE FOOD DETAILS WHICH ARE EXPIRED</h1>
                        <p style="color:aliceblue">
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="true" EnableModelValidation="true" DataKeyNames="fid" DataSourceID="SqlDataSource1" Height="100px" Width="1450px">
                                <Columns>
                                    <asp:BoundField DataField="fid" HeaderText="Food Id"  SortExpression="fid"  HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White"/>
                                    <asp:BoundField DataField="name" HeaderText="Donor's Name" SortExpression="name" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White"/>
                                    <asp:BoundField DataField="phno" HeaderText="Phone Number" SortExpression="phno" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:BoundField DataField="address" HeaderText="Address" SortExpression="address" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:BoundField DataField="ftype" HeaderText="Food Type" SortExpression="ftype" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:BoundField DataField="number" HeaderText="No. Of People That Can Be Fed" SortExpression="number" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:ImageField DataImageUrlField="fimage" HeaderText="Image" SortExpression="fimage" ControlStyle-Height="100" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:BoundField DataField="pdate" HeaderText="Prepare Date" SortExpression="pdate" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White"/>
                                    <asp:BoundField DataField="expirydate" HeaderText="Expiry Date" SortExpression="expirydate" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                    <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                                </Columns>
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [fid], [name], [phno], [address], [ftype], [number], [fimage], [pdate], [expirydate], [status] FROM [fdetails]" DeleteCommand="DELETE FROM [fdetails] where [fid]=@fid"></asp:SqlDataSource>
                        </p>
        
                            
                            </form>
     </body>
    </html>

