<%@ Page Language="C#" AutoEventWireup="true" CodeFile="aorphanage.aspx.cs" Inherits="aorphanage" %>

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>WARM HEARTS</title>
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="assets/css/fontawesome.css">
    <link rel="stylesheet" href="assets/css/templatemo-grad-school.css">
    <link rel="stylesheet" href="assets/css/owl.css">
    <link rel="stylesheet" href="assets/css/lightbox.css">
<!--
    
TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
      </head>

  <body style="background-image:url(assets/images/choosing-bg.jpg)">


      <form id="form1" runat="server">


      <!--header-->
      <header class="main-header clearfix" >
          <div class="logo">
              <a href="#" style="font-size:larger;"><em>AD</em>MIN</a>
          </div>
     <nav id="nav" class="main-nav" role="navigation">
              <ul class="main-menu">
                  <li><a href="admin.aspx">Home</a></li>
                  <li><a href="adonordetails.aspx">Donor's details</a></li>
                  <li><a href="arecdetails.aspx">Receivers details</a></li>
                  
                  <li><a href="aeditpwd.aspx">Edit Password</a></li>
                  <li><a href="ablog.aspx">Edit Blog</a></li>
                  <li><a href="aorphanage.aspx">Edit Orphanage</a></li>
                  <li><a href="aexpire.aspx">Delete Food Details</a></li>
                  <!-- <li><a href="#section5">Video</a></li> -->
                  
                  
            
                  <li><a href="signin.aspx">Logout</a></li>
              </ul>
          </nav>

      </header>

      <!-- ***** Main Banner Area Start ***** -->
      <!-- ***** Main Banner Area End ***** -->


      <!-- Scripts -->
      <!-- Bootstrap core JavaScript -->
      <script src="vendor/jquery/jquery.min.js"></script>
      <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

      <script src="assets/js/isotope.min.js"></script>
      <script src="assets/js/owl-carousel.js"></script>
      <script src="assets/js/lightbox.js"></script>
      <script src="assets/js/tabs.js"></script>
      <script src="assets/js/video.js"></script>
      <script src="assets/js/slick-slider.js"></script>
      <script src="assets/js/custom.js"></script>
      <script>
          //according to loftblog tut
          $('.nav li:first').addClass('active');

          var showSection = function showSection(section, isAnimate) {
              var
                  direction = section.replace(/#/, ''),
                  reqSection = $('.section').filter('[data-section="' + direction + '"]'),
                  reqSectionPos = reqSection.offset().top - 0;

              if (isAnimate) {
                  $('body, html').animate({
                      scrollTop: reqSectionPos
                  },
                      800);
              } else {
                  $('body, html').scrollTop(reqSectionPos);
              }

          }; 

          $(window).scroll(function () {
              checkSection();
          });
      </script>

    

          <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1"    Height="100px" Width="1250px" AutoGenerateDeleteButton="True"  AutoGenerateEditButton="True" style="margin-left: 158px; margin-top: 329px" DataKeyNames="id" EnableModelValidation="true" >
              <Columns>
                  <asp:BoundField DataField="id" HeaderText="ID" SortExpression="id" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                  <asp:BoundField DataField="name" HeaderText="NAME" SortExpression="name" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                  <asp:BoundField DataField="phno" HeaderText="PHONE NUMBER" SortExpression="phno" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                  <asp:BoundField DataField="email" HeaderText="EMAIL ID" SortExpression="email" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />
                  <asp:BoundField DataField="address" HeaderText="ADDRESSS" SortExpression="address" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White"/>
                  <asp:BoundField DataField="descr" HeaderText="REQUIREMENTS" SortExpression="descr" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White"/>
                  <asp:ImageField DataImageUrlField="oimage"  ControlStyle-Height="100" HeaderText="IMAGE" SortExpression="oimage" HeaderStyle-ForeColor="White" ItemStyle-ForeColor="White" />                  

              </Columns>
          </asp:GridView>
          <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [orphanage]" DeleteCommand="DELETE FROM [orphanage] where [id]=@id"></asp:SqlDataSource>
    

    </form>
</body>
</html>
